sudo: false

language: c

os:
  - linux

env:
  global:
    - secure: QCJ9ouBooLYThzTQ1hLfj/Z4eM1kL/BXOamtxIOfGdaRm03AYLUUIKv3/GPpRbP/yBC9GmUVymYPbJPNk8wjHod6T4vs/uQu/TUWm57Rv1TfLFERajiYEHxv/eHyatj7GEbBJjsVf/+BAsTy78y3V9Ny6CaY3oyWIeta0NhEBTg2AKo11DsxVPmcF7y6Uj8lste7Hn4Ly4aZDmNBNvP8ZWsGLwvqmRFl00j6fZbBr19oA4q+AJ7frcBSWG72KeIWKxzd0MUzKcIz2BoUByO5Q+8dCJ2RsCCtcKCMMOlPO6vKvNgiLAP91R4xDCCDEi5+DrV+zarEOCNlqdiUoB0GbLbmJaRNqUAVBldi8ePzCLahloB64oOoqmdwksXYuUCHaXtLtjo9twOpdWIxXQTROy+BS/YsX0fEYuygL9jTcIvAamZ8aPowcYnBH+knQ1Am0BiFYKIcqjc6JUF+Z5iKrpqysXYs3OuRRHsMWWhzBjV8+gvyzMAnifV6x71jMno1BuIKZj3PL/aMyG9GzSx1Archk3ceICfqRI73G8q3iEQomWZcwYIS3UNEvQLOXKnJvuA8qdynnYmNVxV+4B4z3BCxQYsWxOkrrq6Sdp9GMTMMBZ+7cPr2kT3SkpW1rCXXFSTYMTYiGYxLRxxTl/ivzsNxej34uMlxO9pmDcoOuG8=

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - gfortran-5
      - python-pip
      - python-virtualenv
      - graphviz

cache:
  apt: true
  pip: true
  directories:
    - $HOME/.cache/pip
    - $HOME/.local

install:
  - export LOCAL_BIN=$HOME/.local/bin
  - export PATH=$LOCAL_BIN:/usr/local/bin:/usr/bin:$PATH
  - if [ ! -d $HOME/venv ]; then virtualenv $HOME/venv; fi
  - if [ -e $LOCAL_BIN/gcov ]; then rm $LOCAL_BIN/gcov; fi
  - ln -s `which gcov-5` $LOCAL_BIN/gcov
#  - source $HOME/venv/bin/activate
  - pip install --user --upgrade graphviz
  - pip install --user --upgrade ford && ford --version
  - pip install --user --upgrade ghp-import
  - pip install --user --upgrade codecov
  - |
    if [ ! -d $HOME/pFUnit ]; then
      git clone git://git.code.sf.net/p/pfunit/code $HOME/pFUnit
      cd $HOME/pFUnit
    else
      cd $HOME/pFUnit
      git pull
    fi
  - export F90_VENDOR=GNU
  - export F90=gfortran-5
  - make tests
  - make install INSTALL_DIR=$LOCAL_BIN/pfunit-serial
  - export PFUNIT=$LOCAL_BIN/pfunit-serial
  - cd -

script:
  - make tests

after_success:
  - echo "SUCCESS! Once the project is further along I'll regenerate and push documentation"
  - make gcov
  - codecov -X gcov
  - ford doc.md
  - git config user.name "Travis CI"
  - git config user.email "cmacmackin@gmail.com"
  - git pull origin gh-pages
  - ghp-import doc -m "Documentation regenerated by TravisCI, `date`"
  - git push --quiet origin gh-pages > /dev/null 2>&1

