sudo: false

language: c

os:
  - linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - gfortran-5
      - python-pip
      - python-virtualenv
      - graphviz

cache:
  apt: true
  pip: true
  directories:
    - $HOME/.cache/pip
    - $HOME/.local

install:
  - export LOCAL_BIN=$HOME/.local/bin
  - export PATH=$LOCAL_BIN:/usr/local/bin:/usr/bin:$PATH
  - if [ ! -d $HOME/venv ]; then virtualenv $HOME/venv; fi
  - ln -s `which gcov-5` $LOCAL_BIN/gcov
#  - source $HOME/venv/bin/activate
  - pip install --user --upgrade graphviz
  - pip install --user --upgrade ford && ford --version
  - pip install --user --upgrade ghp-import
  - pip install --user --upgrade codecov
  - |
    if [ ! -d $HOME/pFUnit ]; then
      git clone git://git.code.sf.net/p/pfunit/code $HOME/pFUnit
      cd $HOME/pFUnit
    else
      cd $HOME/pFUnit
      git pull
    fi
  - export F90_VENDOR=GNU
  - export F90=gfortran-5
  - make tests
  - make install INSTALL_DIR=$LOCAL_BIN/pfunit-serial
  - export PFUNIT=$LOCAL_BIN/pfunit-serial
  - cd -

script:
  - make tests

after_success:
  - echo "SUCCESS! Once the project is further along I'll regenerate and push documentation"
  - make gcov
  - codecov -X gcov

notifications:
  email: True
