sudo: false

language: c

os:
  - linux

env:
  global:
    - GH_REF: github.com/Fortran-FOSS-Programmers/FIAT
    - secure: nsOmeC+uzMWlNpgSuuzHMMxwzFENaAxdbZ+A8VgsNN9UiLm5I49azMCAeohfeX7NO3qubHMuAhKGUepp37vDE2C3n9A+LakhZYP65cfy6KoBtFpFDvmwiOBpHzKdy7X/M1LCLMtvclSvWHy2a5PIY0r5gZ7p58R8RGhFRxkW8Eg1zSdg/Q4EtDE2i5wmNt+HyPxFddparJZxbZ7wDqkzfts1IjJ2LXbwE2iRzEatmfoAZjVUxSVJ+JeevX8O4LPl8kVpYFyo20aT4P6WUs0Vs2IANE4ABsvJZiKtMsMTaQbICapLONtlhg9AYzc50UG43N5ifaNeDt6sYK4XT87Ga55/rIxuRaf7AcBZ4oMvngP8cOQcoNfZHC3Hq/GLMVoueg838p0G4P0i2m8bxCE67oLsW5SlPZuX8LWsoExapkb+fgF1496YGPRe7H/CVcQZlOOwV/ZLAv4DhCKUsWwrORvzOVawXdWq0FrOQWs4leWMYUA3SUEjfzHuOWKSw7yg4ZpTRzNywPdupC+CMWD0FOWJJMq/iWTyrw2IjutiwxSGRhdp57xB8fYqQbdNZDVQr0JdeIRT2CkgnyxNJrUJ9EAZRKmcnbwCgMgrdVojBdwSLm3uu826mkRYEiNxsOMGA7SPQv7sayYgOchzfQib1QlqNQp3NetSd1UmXIhFZ/U=

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - gfortran-5
      - python-pip
      - python-virtualenv
      - graphviz

cache:
  apt: true
  pip: true
  directories:
    - $HOME/.cache/pip
    - $HOME/.local

install:
  - export LOCAL_BIN=$HOME/.local/bin
  - export PATH=$LOCAL_BIN:/usr/local/bin:/usr/bin:$PATH
  - if [ ! -d $HOME/venv ]; then virtualenv $HOME/venv; fi
  - if [ -e $LOCAL_BIN/gcov ]; then rm $LOCAL_BIN/gcov; fi
  - ln -s `which gcov-5` $LOCAL_BIN/gcov
  - if [ -e $LOCAL_BIN/gfortran ]; then rm $LOCAL_BIN/gfortran; fi
  - ln -s `which gfortran-5` $LOCAL_BIN/gfortran
#  - source $HOME/venv/bin/activate
  - pip install --user --upgrade graphviz
  - pip install --user --upgrade ford && ford --version
  - pip install --user --upgrade ghp-import
  - pip install --user --upgrade codecov
  - |
    if [ ! -d $HOME/pFUnit ]; then
      git clone git://git.code.sf.net/p/pfunit/code $HOME/pFUnit
      cd $HOME/pFUnit
    else
      cd $HOME/pFUnit
      git pull
    fi
  - export F90_VENDOR=GNU
  - export F90=gfortran-5
  - make tests
  - make install INSTALL_DIR=$LOCAL_BIN/pfunit-serial
  - export PFUNIT=$LOCAL_BIN/pfunit-serial
  - cd -

script:
  - make tests

after_success:
  - echo "SUCCESS! Once the project is further along I'll regenerate and push documentation"
  - make gcov
  - codecov -X gcov
  - ford doc.md
  - git config user.name "Travis CI"
  - git config user.email "cmacmackin@gmail.com"
  - git pull origin gh-pages
  - ghp-import doc -m "Documentation regenerated by TravisCI, `date`"
  - git push "https://${GH_TOKEN}@${GH_REF}" gh-pages

